apiVersion: batch/v1
kind: Job
metadata:
  name: "demo-job"
spec:
  template:
    spec:
      containers:
        - name: aws
          image:  ubuntu:latest
          command: ["aws", "s3", "ls"]
      restartPolicy: Never
      