name: Destroy Terraform Resources

on:
    workflow_dispatch:

jobs:
    Destroy:
        name: Terraform Destroy
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: src/terraform
        steps:
            - name: Configure AWS Credentials with Secrets Region
              uses: aws-actions/configure-aws-credentials@v4
              with: 
                role-to-assume: ${{ vars.AWS_ROLE_ARN }}
                aws-region: ${{ vars.AWS_REGION }}
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
            
            - name: Terraform Init
              run: |
                terraform init
            - name: Terraform Destroy
              run: |
                terraform destroy -auto-approve